# Generated by Django 3.1.7 on 2021-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_replying_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_tweet_replies_+', to='tweet.Tweet'),
        ),
    ]
