# Generated by Django 3.1.7 on 2021-03-05 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_auto_20210305_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='followers',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
