# Generated by Django 3.1.7 on 2021-03-05 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0004_auto_20210305_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
