# Generated by Django 3.1.7 on 2021-03-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0005_auto_20210305_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
