# Generated by Django 3.1.7 on 2021-03-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0006_twitteruser_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='photo_url',
            field=models.URLField(blank=True, default='https://cdn3.iconfinder.com/data/icons/galaxy-open-line-gradient-i/200/contacts-512.png'),
        ),
    ]
